const ASCII = {
    "0": "48",
    "1": "49",
    "2": "50",
    "3": "51",
    "4": "52",
    "5": "53",
    "6": "54",
    "7": "55",
    "8": "56",
    "9": "57",
    "": "127",
    " ": "32",
    "!": "33",
    "\"": "34",
    "#": "35",
    "$": "36",
    "%": "37",
    "&": "38",
    "'": "39",
    "(": "40",
    ")": "41",
    "*": "42",
    "+": "43",
    ",": "44",
    "-": "45",
    ".": "46",
    "/": "47",
    ":": "58",
    ";": "59",
    "<": "60",
    "=": "61",
    ">": "62",
    "?": "63",
    "@": "64",
    "A": "65",
    "B": "66",
    "C": "67",
    "D": "68",
    "E": "69",
    "F": "70",
    "G": "71",
    "H": "72",
    "I": "73",
    "J": "74",
    "K": "75",
    "L": "76",
    "M": "77",
    "N": "78",
    "O": "79",
    "P": "80",
    "Q": "81",
    "R": "82",
    "S": "83",
    "T": "84",
    "U": "85",
    "V": "86",
    "W": "87",
    "X": "88",
    "Y": "89",
    "Z": "90",
    "[": "91",
    "\\": "92",
    "]": "93",
    "^": "94",
    "_": "95",
    "`": "96",
    "a": "97",
    "b": "98",
    "c": "99",
    "d": "100",
    "e": "101",
    "f": "102",
    "g": "103",
    "h": "104",
    "i": "105",
    "j": "106",
    "k": "107",
    "l": "108",
    "m": "109",
    "n": "110",
    "o": "111",
    "p": "112",
    "q": "113",
    "r": "114",
    "s": "115",
    "t": "116",
    "u": "117",
    "v": "118",
    "w": "119",
    "x": "120",
    "y": "121",
    "z": "122",
    "{": "123",
    "|": "124",
    "}": "125",
    "~": "126"
};


const opcodetable = [
    {memoNic: "FIX", format: "1", obCode: "C4"},
    {memoNic: "FLOAT", format: "1", obCode: "C0"},
    {memoNic: "HIO", format: "1", obCode: "F4"},
    {memoNic: "NORM", format: "1", obCode: "C8"},
    {memoNic: "SIO", format: "1", obCode: "F0"},
    {memoNic: "TIO", format: "1", obCode: "F8"},
    {memoNic: "ADDR", format: "2", obCode: "90"},
    {memoNic: "CLEAR", format: "2", obCode: "B4"},
    {memoNic: "COMPR", format: "2", obCode: "A0"},
    {memoNic: "DIVR", format: "2", obCode: "9C"},
    {memoNic: "MULR", format: "2", obCode: "98"},
    {memoNic: "RMO", format: "2", obCode: "AC"},
    {memoNic: "SHIFTL", format: "2", obCode: "A4"},
    {memoNic: "SHIFTR", format: "2", obCode: "A8"},
    {memoNic: "SUBR", format: "2", obCode: "94"},
    {memoNic: "SVC", format: "2", obCode: "B0"},
    {memoNic: "TIXR", format: "2", obCode: "B8"},
    {memoNic: "ADD", format: "3", obCode: "18"},
    {memoNic: "ADDF", format: "3", obCode: "58"},
    {memoNic: "AND", format: "3", obCode: "40"},
    {memoNic: "COMP", format: "3", obCode: "28"},
    {memoNic: "COMPF", format: "3", obCode: "88"},
    {memoNic: "DIV", format: "3", obCode: "24"},
    {memoNic: "DIVF", format: "3", obCode: "64"},
    {memoNic: "J", format: "3", obCode: "3C"},
    {memoNic: "JEQ", format: "3", obCode: "30"},
    {memoNic: "JGT", format: "3", obCode: "34"},
    {memoNic: "JLT", format: "3", obCode: "38"},
    {memoNic: "JSUB", format: "3", obCode: "48"},
    {memoNic: "LDA", format: "3", obCode: "00"},
    {memoNic: "LDB", format: "3", obCode: "68"},
    {memoNic: "LDCH", format: "3", obCode: "50"},
    {memoNic: "LDF", format: "3", obCode: "70"},
    {memoNic: "LDL", format: "3", obCode: "08"},
    {memoNic: "LDS", format: "3", obCode: "6C"},
    {memoNic: "LDT", format: "3", obCode: "74"},
    {memoNic: "LDX", format: "3", obCode: "04"},
    {memoNic: "LPS", format: "3", obCode: "D0"},
    {memoNic: "MUL", format: "3", obCode: "20"},
    {memoNic: "MULF", format: "3", obCode: "60"},
    {memoNic: "OR", format: "3", obCode: "44"},
    {memoNic: "RD", format: "3", obCode: "D8"},
    {memoNic: "RSUB", format: "3", obCode: "4C"},
    {memoNic: "SSK", format: "3", obCode: "EC"},
    {memoNic: "STA", format: "3", obCode: "0C"},
    {memoNic: "STB", format: "3", obCode: "78"},
    {memoNic: "STCH", format: "3", obCode: "54"},
    {memoNic: "STF", format: "3", obCode: "80"},
    {memoNic: "STI", format: "3", obCode: "D4"},
    {memoNic: "STL", format: "3", obCode: "14"},
    {memoNic: "STS", format: "3", obCode: "7C"},
    {memoNic: "STSW", format: "3", obCode: "E8"},
    {memoNic: "STT", format: "3", obCode: "84"},
    {memoNic: "STX", format: "3", obCode: "10"},
    {memoNic: "SUB", format: "3", obCode: "1C"},
    {memoNic: "SUBF", format: "3", obCode: "5C"},
    {memoNic: "TD", format: "3", obCode: "E0"},
    {memoNic: "TIX", format: "3", obCode: "2C"},
    {memoNic: "WD", format: "3", obCode: "DC"}
];

const reg = [["A", "X", "L", "B", "S", "T", "F"], [0, 1, 2, 3, 4, 5, 6]];

class flags {
    constructor() {
        this.n = 0;
        this.i = 0;
        this.x = 0;
        this.b = 0;
        this.p = 0;
        this.e = 0;
    }

    n;
    i;
    x;
    b;
    p;
    e;
}
